### ISSUE TITLE
Hide dials to see the Background Image not just for Bing

### ISSUE THREAD

**Issue by Delyrio** [fastaddons/GroupSpeedDial#362]
I am pretty sure this option (Mentioned in the title) used to work for "Select background Image from file" but it only works for "Bing image of the day".

To be fair, no idea when it stopped working but it would be good to have the option to hide dials to see the background for all the background choices.

Cheers

**Comment by Juraj-Masiar** [comment]
Hello,
Yes, the option has been removed because many people were confused when they changed / disabled the background but the hiding stayed enabled.
I will need to move it up (or down) so that it's visible for each background type.

But until then, you can use a simple workaround - open Options page / General / Custom CSS styles, and paste there this:
```css
html {
    & > body > * {
        opacity: 0;
        transition: opacity 0.1s ease-in;
    }
    &:hover > body > * {
        opacity: 1;
        transition: opacity 0.1s;
    }
}
```
