### ISSUE TITLE
Dial's border color on mouse hover

### ISSUE THREAD

**Issue by AlbatorV** [fastaddons/GroupSpeedDial#384]
Hello
Little request about "Mouse over effects" : can you add option to choose color of dial’s border when hover it please.
Regards

**Comment by Juraj-Masiar** [comment]
Oh man :D, the border color on hover is automatically set based on the border color.
The best I can do is give you "Custom CSS styles" (enter it in Options page / General / "Custom CSS styles" field)
```css
.dials > a.dial:is(:focus, :hover):not(.small_dials) .border_target {
  border: 1px solid #00ff00;
}
```
This will change the on-hover color to Green. You can customize the color by changing the `#00ff00` string, you can also use `hsl(50 80% 40%)` or other color syntax you prefer. More info:
https://developer.mozilla.org/en-US/docs/Web/CSS/color_value
